#+OPTIONS: toc:nil num:nil
#+STARTUP: showall indent
#+STARTUP: hidestars
#+BEGIN_EXPORT html
---
layout: portfolio
title: ACM SigMusic Grand Piano
summary:
  type: Web app
  language: Javascript, HTML
  status: exhibited at EOH
  description: >-
    Grand Piano is a project by ACM SigMusic for Engineering Open House 2017 at UIUC.
    I participated in the design of visual elements and music generation logic.
    I myself designed the Web app code structure.
  images:
    - key: Screenshots
      content: 
        - url: /assets/grand_piano_1.png
          name: grand piano screenshot
---
#+END_EXPORT

[[http://grand-piano-branch.herokuapp.com/]]

* Web app for Engineering Open House 2017
  Grand Piano is an interactive music generation experience by ACM SigMusic at
  UIUC Engineering Open House 2017. This project consists of the following
  parts:
  - Web app for piano display, interactive game logic, and sound generation
  - Algorithms for music generation logic
  - Floor piano made with sensors and circuits
  - Data transmission from hardware to the web app.

  I worked on the first 2 parts. We collaborated with electrical engineers on
  the team to complete the project. Here is my work:

  - build a game engine for the exhibit.
  - Designed and Implemented an algorithm for music chord progression generation
    based on classical music theories.
  - Proposed and refined the game idea for the interactive exhibit.
  - Designed and participated in the implementation of the game loop structure.
  - Denoised hardware input and tuned implementations on the fly when facing
    hardware failures during the exhibit.

#+BEGIN_EXPORT html
<div style="position: relative; width: 100%; height: 0; padding-bottom: 56.25%;">
<iframe id="ytplayer" type="text/html" width="100%" height="100%" style="position: absolute" allowfullscreen
  src="https://www.youtube.com/embed/FVedboVVNAg"
  frameborder="0">
</iframe>
</div>
#+END_EXPORT
